name: Set up Node, install packages, and build project
description: Install Node LTS and project dependencies, then build the project

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: |
        npm ci
        npm run build
      shell: bash
